version: '3.8'

services:

  ex-fe:
    container_name: ex-fe
    build:
      context: ./example-frontend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - REQUEST_ORIGIN=ttp://localhost:5000

  ex-be:
    container_name: ex-be
    build:
      context: ./example-backend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

# relies on on the Dockerfiles from the directories
# no volumes because it doesn't save any data